sudo: required
dist: trusty
language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then sudo apt-get install php5-intl; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then sudo apt-get install php-intl; fi
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)