sudo: false
language: php
php:
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

before_script:
  - pecl channel-update pecl.php.net
  - printf "\n" | pecl install intl
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)